apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fnnl20071-go
  janus-idp.io/tekton: fnnl20071-go
  backstage.io/kubernetes-id: fnnl20071-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fnnl20071-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
