apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fnnl20071-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fnnl20071-go 
  name: fnnl20071-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fnnl20071-go 
